Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	sort_gene_family
	2

rule sort_gene_family:
    input: tmp/roary/gene_presence_absence.csv, tmp/prokka/CH2500/CH2500.ffn, tmp/prokka/CH2502/CH2502.ffn, tmp/prokka/CH2522/CH2522.ffn, tmp/prokka/F1659/F1659.ffn
    output: tmp/aln.list
    jobid: 1
    wildcards: TMP_D=tmp

    Error in rule sort_gene_family:
        jobid: 1
        output: tmp/aln.list

RuleException:
CalledProcessError in line 35 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  /home/thkuo/miniconda3/envs/phypal/bin/python /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake.8a2itm22.makeGroupAln.py ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk", line 35, in __rule_sort_gene_family
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job sort_gene_family since they might be corrupted:
tmp/aln.list
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake/log/2018-07-15T124019.135351.snakemake.log
