Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	aln_to_vcf
	1	create_indel_table
	1	sort_gene_family
	1	vcf_to_indels
	5

rule sort_gene_family:
    input: tmp/roary/gene_presence_absence.csv, tmp/CH2500/spades/prokka/de_novo.ffn, tmp/CH2502/spades/prokka/de_novo.ffn, tmp/CH2522/spades/prokka/de_novo.ffn, tmp/F1659/spades/prokka/de_novo.ffn
    output: tmp/aln.list
    jobid: 13
    wildcards: TMP_D=tmp

Finished job 13.
1 of 5 steps (20%) done

rule aln_to_vcf:
    input: tmp/aln.list
    output: tmp/aln_vcf.list
    jobid: 8
    wildcards: TMP_D=tmp

    Error in rule aln_to_vcf:
        jobid: 8
        output: tmp/aln_vcf.list

RuleException:
CalledProcessError in line 68 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  
        parallel -j 16 'java -jar jvarkit/dist/msa2vcf.jar         < "{}.aln" > "{}.vcf"' ::: `cat tmp/aln.list|         sed 's/\.aln$//'`
        cat tmp/aln.list | sed 's/\.aln$/.vcf/'         > tmp/aln_vcf.list ' returned non-zero exit status 4.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/CREATE_INDEL_TABLE.smk", line 68, in __rule_aln_to_vcf
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v4/.snakemake/log/2018-08-06T175009.316488.snakemake.log
